const assert = require('assert')
const fs = require('fs')
const path = require('path')
const test = require('node:test')

const runtimeDir = path.join(__dirname, '..')
const pluginDir = path.join(__dirname, '..', '..', 'plugin', 'TonePilotLightroomBridge.lrplugin')

test('插件清单暴露常驻 Agent 控制台入口', () => {
  const info = fs.readFileSync(path.join(pluginDir, 'Info.lua'), 'utf8')

  assert.match(info, /title\s*=\s*"打开 TonePilot Agent 控制台"/)
  assert.match(info, /file\s*=\s*"AgentConsole.lua"/)
  assert.doesNotMatch(info, /TonePilot Agent 调色/)
  assert.doesNotMatch(info, /AgentTune\.lua/)
  assert.doesNotMatch(info, /启动 TonePilot Bridge Worker/)
  assert.doesNotMatch(info, /MenuStartWorker\.lua/)
  assert.strictEqual((info.match(/title\s*=/g) || []).length, 1)
  assert.strictEqual(fs.existsSync(path.join(pluginDir, 'AgentTune.lua')), false)
  assert.strictEqual(fs.existsSync(path.join(pluginDir, 'MenuStartWorker.lua')), false)
})

test('Lightroom Worker 降低选图时的轮询和预览导出压力', () => {
  const configLua = fs.readFileSync(path.join(pluginDir, 'BridgeConfig.lua'), 'utf8')
  const workerLua = fs.readFileSync(path.join(pluginDir, 'BridgeWorker.lua'), 'utf8')

  assert.match(configLua, /pollSeconds\s*=\s*3/)
  assert.match(configLua, /metadataDebugIntervalSeconds\s*=\s*30/)
  assert.match(workerLua, /cachedMetadataDiagnostics/)
  assert.match(workerLua, /lastMetadataDebugKey/)
  assert.doesNotMatch(workerLua, /metadataDebug\s*=\s*metadataDiagnostics\(selected\)/)
  assert.match(workerLua, /requestJpegThumbnail\(1200,\s*1200/)
  assert.match(workerLua, /writeBinaryFile/)
  assert.doesNotMatch(workerLua, /LrExportSession/)
  assert.doesNotMatch(workerLua, /renditions\(\{\s*stopIfCanceled\s*=/)
  assert.doesNotMatch(workerLua, /waitForRender/)
  assert.doesNotMatch(workerLua, /LR_jpeg_quality\s*=/)
  assert.doesNotMatch(workerLua, /LR_size_maxWidth\s*=/)
  assert.doesNotMatch(workerLua, /LR_size_maxHeight\s*=/)
})

test('Agent 控制台只渲染同一照片会话的前后对比', () => {
  const serverJs = fs.readFileSync(path.join(runtimeDir, 'src', 'bridge-runtime.js'), 'utf8')

  assert.match(serverJs, /photoKey:\s*session\.photoKey/)
  assert.match(serverJs, /comparisonPhotoKey/)
  assert.match(serverJs, /setComparisonLabels/)
  assert.match(serverJs, /version\.photoKey\s*!==\s*session\.photoKey/)
  assert.match(serverJs, /beforePreviewPane\.dataset\.label/)
  assert.match(serverJs, /afterPreviewPane\.dataset\.label/)
  assert.match(serverJs, /height:\s*100%/)
  assert.match(serverJs, /object-fit:\s*contain/)
})

test('Agent 控制台使用 Lightroom 深色面板视觉 token', () => {
  const consoleLua = fs.readFileSync(path.join(pluginDir, 'AgentConsole.lua'), 'utf8')
  const initLua = fs.readFileSync(path.join(pluginDir, 'Init.lua'), 'utf8')
  const shutdownLua = fs.readFileSync(path.join(pluginDir, 'Shutdown.lua'), 'utf8')
  const workerLua = fs.readFileSync(path.join(pluginDir, 'BridgeWorker.lua'), 'utf8')
  const serverJs = fs.readFileSync(path.join(runtimeDir, 'src', 'bridge-runtime.js'), 'utf8')
  const launcher = fs.readFileSync(path.join(pluginDir, 'StartBridgeAndConsole.ps1'), 'utf8')

  assert.match(consoleLua, /LrHttp/)
  assert.match(consoleLua, /openUrlInBrowser/)
  assert.match(consoleLua, /LrTasks\.startAsyncTask/)
  assert.doesNotMatch(consoleLua, /LrShell/)
  assert.doesNotMatch(consoleLua, /openURL/)
  assert.match(consoleLua, /\/agent-console/)
  assert.match(consoleLua, /StartBridgeAndConsole\.ps1/)
  assert.match(consoleLua, /TonePilotDarkTheme/)
  assert.match(consoleLua, /深灰/)
  assert.match(consoleLua, /#2b2b2b/)
  assert.match(consoleLua, /#d6d6d6/)
  assert.match(launcher, /tonepilot-local-runtime/)
  assert.match(launcher, /tonepilot-lightroom-bridge/)
  assert.match(launcher, /agent-console/)
  assert.match(initLua, /_G\.TonePilotBridgeWorker/)
  assert.match(initLua, /existingWorker\.stop/)
  assert.match(shutdownLua, /_G\.TonePilotBridgeWorker/)
  assert.doesNotMatch(shutdownLua, /dofile/)
  assert.match(workerLua, /selected-photo\.json/)
  assert.match(workerLua, /selected-preview\.jpg/)
  assert.match(workerLua, /previewFileName/)
  assert.match(workerLua, /previewUrl/)
  assert.match(workerLua, /apply-preview-error\.txt/)
  assert.doesNotMatch(workerLua, /processJobs/)
  assert.doesNotMatch(workerLua, /applyAndExport/)
  assert.doesNotMatch(workerLua, /toDevelopSettings/)
  assert.match(workerLua, /getTargetPhotos/)
  assert.match(workerLua, /withReadAccessDo\(function\(\)/)
  assert.doesNotMatch(workerLua, /withReadAccessDo\("TonePilot 读取当前照片信息"/)
  assert.match(workerLua, /getRawMetadata/)
  assert.match(workerLua, /cameraMake/)
  assert.match(workerLua, /cameraModel/)
  assert.match(workerLua, /firstNonEmpty/)
  assert.match(workerLua, /metadataDebug/)
  assert.match(workerLua, /metadataDiagnostics/)
  assert.match(workerLua, /metadataProbe/)
  assert.match(workerLua, /LrTasks\.pcall\(function\(\)\s*return photo:getFormattedMetadata/s)
  assert.match(workerLua, /LrTasks\.pcall\(function\(\)\s*return photo:getRawMetadata/s)
  assert.doesNotMatch(workerLua, /local formattedOk, formattedValue = pcall\(function\(\)\s*return photo:getFormattedMetadata/s)
  assert.doesNotMatch(workerLua, /local rawOk, rawValue = pcall\(function\(\)\s*return photo:getRawMetadata/s)
  assert.match(workerLua, /developPreviewSignature/)
  assert.match(workerLua, /workerBuild/)
  assert.match(workerLua, /previewError/)
  assert.match(workerLua, /requestJpegThumbnail/)
  assert.match(workerLua, /writeBinaryFile/)
  assert.doesNotMatch(workerLua, /LrExportSession/)
  assert.doesNotMatch(workerLua, /renditions\(\{\s*stopIfCanceled\s*=/)
  assert.doesNotMatch(workerLua, /waitForRender/)
  assert.doesNotMatch(workerLua, /now - lastPreviewAt > 12/)
  assert.match(serverJs, /agent-console/)
  assert.match(serverJs, /grid-template-columns:\s*minmax\(0,\s*1fr\)\s+minmax\(0,\s*1fr\)/)
  assert.match(serverJs, /previewImage/)
  assert.match(serverJs, /afterPreviewImage/)
  assert.match(serverJs, /beforePreviewUrl/)
  assert.match(serverJs, /afterPreviewUrl/)
  assert.match(serverJs, /sessions\.json/)
  assert.match(serverJs, /stablePhotoKey/)
  assert.match(serverJs, /ensureSessionBaseline/)
  assert.match(serverJs, /recordSessionVersion/)
  assert.match(serverJs, /versionList/)
  assert.match(serverJs, /quickAction/)
  assert.match(serverJs, /currentPreviewUrl/)
  assert.match(serverJs, /payload\.previewUrl !== currentPreviewUrl/)
  assert.match(serverJs, /lastStablePreviewUrl/)
  assert.doesNotMatch(serverJs, /Agent 流程/)
  assert.doesNotMatch(serverJs, /type="file"/)
  assert.doesNotMatch(serverJs, /上传/)
  assert.match(serverJs, /api\/lightroom\/selected-photo/)
  assert.match(serverJs, /api\/lightroom-agent\/chat/)
  assert.match(serverJs, /api\/runtime\/config/)
  assert.match(serverJs, /createModelTune/)
  assert.match(serverJs, /createRuleTune/)
  assert.doesNotMatch(serverJs, /api\/lightroom-agent\/tune/)
  assert.doesNotMatch(serverJs, /backendBaseUrl/)
  assert.doesNotMatch(serverJs, /createRenderJob/)
  assert.doesNotMatch(serverJs, /pathname === '\/render'/)
})

test('Bridge 根入口只负责加载运行时模块', () => {
  const serverEntry = fs.readFileSync(path.join(runtimeDir, 'server.js'), 'utf8')

  assert.match(serverEntry, /require\('\.\/src\/bridge-runtime'\)/)
  assert.doesNotMatch(serverEntry, /http\.createServer/)
  assert.doesNotMatch(serverEntry, /agentConsoleHtml/)
})
